#!/bin/sh

source /etc/dropbear/init-env

while [ ! -b /dev/mapper/${KOPT_cryptdm} ]; do
	/sbin/nlplug-findfs $cryptopts -p /sbin/mdev ${KOPT_debug_init:+-d} $KOPT_root
	sleep 2
done

killall -9 nlplug-findfs
killall -9 dropbear
